= Comment bien préparer un salon technologique ?

Talk ayant pour objectif d'expliquer l'état d'esprit à avoir pour aborder un salon technologique (comme un Devoxx) :

* ce qu'il est bon d'en retirer
* les "pièges" à éviter
* la préparation en amont du salon

Les slides sont directement accessibles à l'URL https://ardemius.github.io/bien-preparer-un-salon-technologique/slides.html, à l'aide des *GitHub pages* du projet.

== Création des slides

Ces slides utilisent la stack technique http://asciidoctor.org/[*Asciidoctor*] + backend https://github.com/asciidoctor/asciidoctor-reveal.js[*reveal.js*]. +
Pour plus d'informations sur cette dernière (installation, outils associés, exemples, etc.), se référer à https://github.com/Ardemius/asciidoctor-presentation#slides-rendering-with-revealjs[ma présentation] sur le sujet.

Néanmoins, à l'aide de l'image *Docker Asciidoctor*, cela se résume maintenant à 2 petites commandes 😉 (une fois que vous avez cloné le repo) : 

1. lancement du container : 
+
	docker run -it -v <path-to-the-cloned-repo>/docs:/documents/ asciidoctor/docker-asciidoctor

2. génération des slides : 
+
	asciidoctor-revealjs bien-preparer-un-salon-technologique.adoc -o slides.html

