= Comment bien préparer un salon technologique ?

Talk ayant pour objectif d'expliquer l'état d'esprit à avoir pour aborder un salon technologique (comme un Devoxx) :

* ce qu'il est bon d'en retirer
* les "pièges" à éviter
* la préparation en amont du salon

Les slides sont directement accessibles à l'URL https://ardemius.github.io/bien-preparer-un-salon-technologique/slides.html, à l'aide des *GitHub pages* du projet.

J'ai présenté ce talk au *CFP de Devoxx France 2022* qui l'a retenu mais en me demandant de le transformer en *article pour le blog de Devoxx France*. +
Une version de travail de ce dernier est également disponible dans les GitHub pages du projet, à l'URL : https://ardemius.github.io/bien-preparer-un-salon-technologique/article.html

== Création des slides

Ces slides utilisent la stack technique http://asciidoctor.org/[*Asciidoctor*] + backend https://github.com/asciidoctor/asciidoctor-reveal.js[*reveal.js*]. +
Pour plus d'informations sur cette dernière (installation, outils associés, exemples, etc.), se référer à https://github.com/Ardemius/asciidoctor-presentation#slides-rendering-with-revealjs[ma présentation] sur le sujet.

Néanmoins, à l'aide de l'image *Docker Asciidoctor*, cela se résume maintenant à 3 petites commandes 😉 : 

1. clone du repo avec récupération du contenu du submodule reveal.js : 
+
	git clone --recursive https://github.com/Ardemius/bien-preparer-un-salon-technologique.git

2. lancement du container : 
+
	docker run -it -v <path-to-the-cloned-repo>/docs:/documents/ asciidoctor/docker-asciidoctor

3. génération des slides : 
+
	asciidoctor-revealjs bien-preparer-un-salon-technologique.adoc -o slides.html

